import uuid
from dataclasses import dataclass

from backend.services.recommendation_service.app.domain.intelligence_context import IntelligenceContext


@dataclass(frozen=True)
class RecommendationExecutionRequest:
    """
    Recommendation Execution Request DTO (Application-owned)

    Operational Purpose:
    The "Application request" the Infrastructure Event Consumer produces
    from a deserialized `BusinessImpactCompleted` transport payload, and
    the sole input `RecommendationLifecycleService.execute()` accepts. It
    is the Consumer's entire "translate transport payload into an
    Application request" responsibility, expressed as a type -- once this
    object exists, nothing downstream needs to know anything about
    transport, wire formats, or messaging. The same role
    `EvaluationExecutionRequest` plays in `evaluation_service`.

    Architectural Boundaries:
    - `event_id` is the inbound event's own identifier -- the value the
      idempotency check and the database UNIQUE constraint are keyed on.
      It is never generated by this service; it must already exist on the
      event as received.
    - `intelligence_context` is the existing, frozen Step 1
      `IntelligenceContext` Domain Value Object, reused verbatim -- Step 3
      does not change what the Recommendation Engine consumes, only how it
      now arrives.
    """

    event_id: uuid.UUID
    intelligence_context: IntelligenceContext
