"""
Phase 7 Step 3 -- Explainability Contract Validation.

The Business Impact explanation generated by the (frozen) Engine must
survive unchanged through every downstream boundary:

    Engine -> Assessment -> Persistence -> Repository -> REST API -> JSON

These tests verify exact string equality at every hop -- not merely
"non-empty" or "similar" -- across several different engine outcomes (a
fully quiet incident, a fully critical incident, and a mixed-severity
incident), and independently verify that every dimension's own reason,
already decided by its rule, is present verbatim in the final explanation --
proving the explanation aggregates real evidence rather than summarizing or
discarding it.
"""

import json
import uuid
from datetime import datetime, timezone

import pytest

from backend.services.business_impact_service.app.domain.anomaly_metrics import AnomalyMetrics
from backend.services.business_impact_service.app.domain.incident import Incident
from backend.services.business_impact_service.app.domain.root_cause_summary import RootCauseSummary
from backend.services.business_impact_service.app.domain.trend_metrics import TrendMetrics
from backend.services.business_impact_service.app.mappers.output_mapper import BusinessImpactOutputMapper
from backend.services.business_impact_service.app.schemas.business_impact import BusinessImpactAssessmentResponse
from backend.services.business_impact_service.app.services.impact_engine import BusinessImpactEngine, default_rules
from backend.shared.constants.enums.anomaly import AnomalySeverity, AnomalyType
from backend.shared.constants.enums.business_impact_assessment import BusinessImpactAssessmentStatus
from backend.shared.constants.enums.complaint import UrgencyLabel
from backend.shared.constants.enums.root_cause import RootCause


def _simulate_persistence(entity) -> None:
    """Mimics what a real PostgreSQL flush would populate (see fakes.FakeBusinessImpactRepository.save)."""
    entity.assessment_id = uuid.uuid4()
    entity.status = BusinessImpactAssessmentStatus.ACTIVE
    entity.created_at = datetime.now(timezone.utc)
    entity.updated_at = entity.created_at


def _quiet_scenario():
    """No signal on any dimension -- explanation should read as fully uninformative but still present."""
    incident = Incident(incident_id="INC-QUIET-0001", severity=AnomalySeverity.LOW)
    root_cause = RootCauseSummary(cause=RootCause.UNKNOWN, confidence_score=0, confidence_level="Weak")
    trend_metrics = TrendMetrics(current_volume=0, baseline_volume=0, percentage_change=0.0)
    anomaly_metrics = AnomalyMetrics(
        anomaly_types=(), severity=AnomalySeverity.LOW, affected_customer_count=0,
        sla_breach_count=0, negative_sentiment_ratio=0.0,
    )
    return incident, root_cause, trend_metrics, anomaly_metrics


def _critical_scenario():
    """Every dimension at its most severe."""
    incident = Incident(
        incident_id="INC-CRITICAL-0001",
        severity=AnomalySeverity.CRITICAL,
        regions=("us-east", "us-west", "eu"),
        urgency_levels=(UrgencyLabel.CRITICAL,),
    )
    root_cause = RootCauseSummary(cause=RootCause.SERVICE_OUTAGE, confidence_score=100, confidence_level="Very High")
    trend_metrics = TrendMetrics(current_volume=1500, baseline_volume=200, percentage_change=650.0)
    anomaly_metrics = AnomalyMetrics(
        anomaly_types=(AnomalyType.COMPLAINT_SPIKE, AnomalyType.SENTIMENT_SHIFT),
        severity=AnomalySeverity.CRITICAL,
        affected_customer_count=1500,
        sla_breach_count=25,
        negative_sentiment_ratio=0.9,
    )
    return incident, root_cause, trend_metrics, anomaly_metrics


def _mixed_scenario():
    """A realistic, partially-informative incident (mirrors fakes.build_realistic_incident_scenario)."""
    incident = Incident(
        incident_id="INC-MIXED-0001",
        severity=AnomalySeverity.CRITICAL,
        regions=("us-east", "us-west"),
        urgency_levels=(UrgencyLabel.CRITICAL,),
    )
    root_cause = RootCauseSummary(cause=RootCause.SERVICE_OUTAGE, confidence_score=90, confidence_level="Very High")
    trend_metrics = TrendMetrics(current_volume=500, baseline_volume=200, percentage_change=150.0)
    anomaly_metrics = AnomalyMetrics(
        anomaly_types=(AnomalyType.COMPLAINT_SPIKE, AnomalyType.REGIONAL_SPIKE, AnomalyType.SENTIMENT_SHIFT),
        severity=AnomalySeverity.CRITICAL,
        affected_customer_count=500,
        sla_breach_count=0,
        negative_sentiment_ratio=0.0,
    )
    return incident, root_cause, trend_metrics, anomaly_metrics


SCENARIOS = {
    "quiet": _quiet_scenario,
    "critical": _critical_scenario,
    "mixed": _mixed_scenario,
}


@pytest.mark.parametrize("scenario_name", list(SCENARIOS.keys()))
def test_explanation_is_preserved_verbatim_from_engine_to_orm_entity(scenario_name):
    incident, root_cause, trend_metrics, anomaly_metrics = SCENARIOS[scenario_name]()
    engine = BusinessImpactEngine(rules=default_rules())

    assessment = engine.analyze(incident, root_cause, trend_metrics, anomaly_metrics)
    entity = BusinessImpactOutputMapper.to_orm(uuid.uuid4(), uuid.uuid4(), assessment)

    assert entity.explanation == assessment.explanation
    assert len(entity.explanation) > 0


@pytest.mark.parametrize("scenario_name", list(SCENARIOS.keys()))
def test_explanation_is_preserved_verbatim_from_orm_entity_to_response_dto(scenario_name):
    incident, root_cause, trend_metrics, anomaly_metrics = SCENARIOS[scenario_name]()
    engine = BusinessImpactEngine(rules=default_rules())

    assessment = engine.analyze(incident, root_cause, trend_metrics, anomaly_metrics)
    entity = BusinessImpactOutputMapper.to_orm(uuid.uuid4(), uuid.uuid4(), assessment)
    _simulate_persistence(entity)

    dto = BusinessImpactAssessmentResponse.model_validate(entity, from_attributes=True)

    assert dto.explanation == entity.explanation == assessment.explanation


@pytest.mark.parametrize("scenario_name", list(SCENARIOS.keys()))
def test_explanation_is_preserved_verbatim_through_json_serialization(scenario_name):
    incident, root_cause, trend_metrics, anomaly_metrics = SCENARIOS[scenario_name]()
    engine = BusinessImpactEngine(rules=default_rules())

    assessment = engine.analyze(incident, root_cause, trend_metrics, anomaly_metrics)
    entity = BusinessImpactOutputMapper.to_orm(uuid.uuid4(), uuid.uuid4(), assessment)
    _simulate_persistence(entity)

    dto = BusinessImpactAssessmentResponse.model_validate(entity, from_attributes=True)
    json_text = dto.model_dump_json()
    decoded = json.loads(json_text)

    # Full JSON encode/decode round trip introduces no truncation, escaping
    # artifact, or reformatting of the explanation text.
    assert decoded["explanation"] == assessment.explanation


@pytest.mark.parametrize("scenario_name", list(SCENARIOS.keys()))
def test_explanation_contains_every_dimension_reason_verbatim(scenario_name):
    """
    The explanation must aggregate each rule's own reason, unmodified --
    never summarize, truncate, or re-derive it. This independently
    re-evaluates each rule (already unit-tested on its own) purely to obtain
    its `.reason` string, then asserts that exact string appears in the
    final explanation produced by the full engine run.
    """
    incident, root_cause, trend_metrics, anomaly_metrics = SCENARIOS[scenario_name]()
    engine = BusinessImpactEngine(rules=default_rules())
    assessment = engine.analyze(incident, root_cause, trend_metrics, anomaly_metrics)

    for rule in default_rules():
        evaluation = rule.evaluate(incident, root_cause, trend_metrics, anomaly_metrics)
        assert evaluation.reason in assessment.explanation, (
            f"{scenario_name}: expected reason for {evaluation.impact_dimension.value!r} "
            f"({evaluation.reason!r}) to appear verbatim in the explanation"
        )
