"""Initial complaint entity

Revision ID: 66239761b187
Revises: 
Create Date: 2026-05-22 22:43:16.757051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66239761b187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('external_reference_id', sa.String(length=255), nullable=True),
    sa.Column('complaint_title', sa.String(length=255), nullable=True),
    sa.Column('complaint_text', sa.Text(), nullable=False),
    sa.Column('complaint_source', sa.String(length=255), nullable=True),
    sa.Column('source_channel', sa.Enum('EMAIL', 'CHAT', 'SUPPORT_TICKET', 'SOCIAL_MEDIA', 'MOBILE_APP', 'WEBSITE_FORM', 'CALL_CENTER', 'MARKETPLACE', 'INTERNAL_SYSTEM', name='sourcechannel'), nullable=True),
    sa.Column('normalized_title', sa.String(length=255), nullable=True),
    sa.Column('normalized_complaint_text', sa.Text(), nullable=True),
    sa.Column('customer_region', sa.String(length=100), nullable=True),
    sa.Column('customer_segment', sa.Enum('INDIVIDUAL', 'PREMIUM', 'ENTERPRISE', 'PARTNER', 'RESELLER', 'UNKNOWN', name='customersegment'), nullable=True),
    sa.Column('customer_type', sa.Enum('NEW_CUSTOMER', 'EXISTING_CUSTOMER', 'HIGH_VALUE_CUSTOMER', 'AT_RISK_CUSTOMER', 'CHURNED_CUSTOMER', 'UNIDENTIFIED', name='customertype'), nullable=True),
    sa.Column('product_category', sa.String(length=255), nullable=True),
    sa.Column('operational_area', sa.Enum('LOGISTICS', 'PAYMENTS', 'CUSTOMER_SUPPORT', 'DELIVERY', 'INVENTORY', 'PRODUCT_QUALITY', 'RETURNS', 'ACCOUNT_MANAGEMENT', 'SUBSCRIPTION_SERVICES', 'TECHNICAL_PLATFORM', name='operationalarea'), nullable=True),
    sa.Column('service_type', sa.Enum('FULFILLMENT', 'PAYMENT_PROCESSING', 'CUSTOMER_SERVICE', 'DELIVERY_OPERATIONS', 'DIGITAL_SERVICES', 'SUBSCRIPTION_MANAGEMENT', 'PLATFORM_OPERATIONS', name='servicetype'), nullable=True),
    sa.Column('event_occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complaint_status', sa.Enum('PENDING', 'INGESTED', 'NORMALIZED', 'ENRICHED', 'ANALYZED', 'CORRELATED', 'ESCALATED', 'RESOLVED', 'ARCHIVED', name='complaintstatus'), nullable=False),
    sa.Column('processing_stage', sa.Enum('RAW_INGESTION', 'PREPROCESSING', 'ENRICHMENT', 'ANOMALY_ANALYSIS', 'BUSINESS_EVALUATION', 'RECOMMENDATION_GENERATION', 'COMPLETED', name='processingstage'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('ingestion_source', sa.String(length=255), nullable=True),
    sa.Column('ingestion_batch_id', sa.String(length=255), nullable=True),
    sa.Column('source_record_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index('ix_complaints_area_occurred_at', 'complaints', ['operational_area', 'event_occurred_at'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_status'), 'complaints', ['complaint_status'], unique=False)
    op.create_index(op.f('ix_complaints_customer_region'), 'complaints', ['customer_region'], unique=False)
    op.create_index(op.f('ix_complaints_event_occurred_at'), 'complaints', ['event_occurred_at'], unique=False)
    op.create_index(op.f('ix_complaints_external_reference_id'), 'complaints', ['external_reference_id'], unique=False)
    op.create_index(op.f('ix_complaints_is_deleted'), 'complaints', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_complaints_operational_area'), 'complaints', ['operational_area'], unique=False)
    op.create_index(op.f('ix_complaints_source_record_hash'), 'complaints', ['source_record_hash'], unique=False)
    op.create_index('ix_complaints_status_occurred_at', 'complaints', ['complaint_status', 'event_occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaints_status_occurred_at', table_name='complaints')
    op.drop_index(op.f('ix_complaints_source_record_hash'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_operational_area'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_is_deleted'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_external_reference_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_event_occurred_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_region'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_status'), table_name='complaints')
    op.drop_index('ix_complaints_area_occurred_at', table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
